### ISSUE TITLE
Graph CNN code for Single style-Shape model

### ISSUE THREAD

**Issue by yuxwind** [chaitanya100100/TailorNet#1]
Great job! The paper reported an experiment of Graph CNN for the style-shape model. It is interesting that MLP outperforms GCN here. I would like to test some ideas based on your GCN network. Would you plan to release its code? It is also good if you can provide detailed network settings. Thanks a lot!

**Comment by chaitanya100100** [comment]
Hi yuxwind,
I am glad that you find our paper interesting. :)

Currently, we don't have any plan to release GraphCNN code. It's not a small code and it requires some preprocessing steps. Including that here would divert the focus of the code. And it's not the main focus of the paper. 

Having said that, I will try to list some key aspects of the Graph CNN we used. It shouldn't take much effort to implement it.

1. We use the formulation of [1] for graph CNN. [2] has done the graphCNN regression on SMPL body, so we followed the same architecture.
2. Our garment template is too high-resolution for training with GraphCNN. So we downsample the template by a factor of 3. [3] might be useful for that.


[1] Thomas N. Kipf and Max Welling. Semi-supervised classification with graph convolutional networks. In International
Conference on Learning Representations (ICLR), 2017.
[2] https://www.seas.upenn.edu/~nkolot/projects/cmr/
[3] https://github.com/anuragranj/coma/blob/master/lib/mesh_sampling.py
