### ISSUE TITLE
real garment

### ISSUE THREAD

**Issue by melih1996** [chaitanya100100/TailorNet#11]
Hi, what is needed to put a real garment on an smpl body model? Do I need a 3d model of the garment to do this without losing texture details?

**Comment by chaitanya100100** [comment]
You can take garment template from [MultiGarmentNet](http://virtualhumans.mpi-inf.mpg.de/mgn/) and put it on the SMPL body in Marvellous Designer simulator. 
No texture is required for simulation.

**Comment by melih1996** [comment]
But what if I want to try my t-shirt bought from a brand using tailornet. Am I supposed to create the rgb image of my t-shirt to some 3d template if so how to do that or I can only try the garments in MGN templates?

**Comment by chaitanya100100** [comment]
Answered here: https://github.com/chaitanya100100/TailorNet/issues/14

**Comment by melih1996** [comment]
Hi, is it enough to change only gamma parameter to transfer garment from multigarmentnet using tailornet? If not, how to do that?
