### ISSUE TITLE
Is it possible to privide the Google drive or BaiduYun link for downing the dataset?

### ISSUE THREAD

**Issue by Amazingren** [chaitanya100100/TailorNet#12]
Thanks for your impressive work, I am very interested in this. However, when I want to have a try and download the dataset, it seems extremely slow, nearly 10KB/s. 

So, I come to seek help, I wonder is there any other faster alternative manner such as Google Drive or BaiduYun to acquire the dataset?

**Comment by chaitanya100100** [comment]
There is no another alternative yet to download the dataset.
I tried to download the dataset right now and I am getting decent download speed. Maybe that slow speed was a one off incident because of the heavy load on the dataset server at that time. Can you try downloading once again? Let me know if the issue still persists.

**Comment by Amazingren** [comment]
> There is no another alternative yet to download the dataset.
> I tried to download the dataset right now and I am getting decent download speed. Maybe that slow speed was a one off incident because of the heavy load on the dataset server at that time. Can you try downloading once again? Let me know if the issue still persists.

Thanks for your reply. I utilize IDM(Internet Download Manager) and assign VPN to it, then it works. Now, I have download the dataset, thanks again! 
Maybe others who also meet this problem(Especially who are in China) can have a try on the following two methods:
(1) Ask a friend abroad to download the dataset and then upload it to Google Drive(only for academic use).
(2) Utilize IDM and assign your VPN setting to it for accelerating.

**Comment by zycliao** [comment]
Hi, we are uploading the dataset to Baidu Yun. 
Link：https://pan.baidu.com/s/14roMijl36ruppRNd3tNC2g 
Password：TLNT
