### ISSUE TITLE
Environment Requirement

### ISSUE THREAD

**Issue by Amazingren** [chaitanya100100/TailorNet#13]
Hi, 
It may be useful and more convenient for others like me(green hand in this field) if you could please provide the environment requirements in detail such as: 
- cuda version
- Pytorch version
- and the version of other libs 
More specifically, maybe a requirments.txt file would be so helpful.

Best,

**Comment by chaitanya100100** [comment]
The repo doesn't use any library which is in development. So installing the latest versions would work. This repo was tested with latest versions of the libraries: psbody.mesh v0.4 , pytorch >= v1.0 , chumpy v0.7 , scipy v1.3 .
There is no separate cuda requirement as long as proper pytorch is installed. Let me know if any latest library is not working.

**Comment by x2z2x2x2** [comment]
> The repo doesn't use any library which is in development. So installing the latest versions would work. This repo was tested with latest versions of the libraries: psbody.mesh v0.4 , pytorch >= v1.0 , chumpy v0.7 , scipy v1.3 .
> There is no separate cuda requirement as long as proper pytorch is installed. Let me know if any latest library is not working.

Hi，
 When I run run_tailornet.py,there are an AttributeError: 'scipy.spatial.transform.rotation.Rotation' object has no attribute 'as_dcm',when it  runing in File "/home/user/quan/TailorNet-master/visualization/blender_renderer.py", line 73, in get_rotmat
    return s.as_dcm().The scipy version which I used is 1.6.2.Could you know what should  I do?
Thanks!

**Comment by x2z2x2x2** [comment]
Like this:
![image](https://user-images.githubusercontent.com/60689500/112977304-776acd80-9188-11eb-8fb6-e2c0201dd163.png)

**Comment by chaitanya100100** [comment]
As noted in https://github.com/chaitanya100100/TailorNet/issues/13#issuecomment-757443982 , scipy 1.3 works.

**Comment by x2z2x2x2** [comment]
Thanks
