### ISSUE TITLE
new garment

### ISSUE THREAD

**Issue by melih1996** [chaitanya100100/TailorNet#14]
I want to try my t-shirt bought from a brand using tailornet. Am I supposed to create the rgb image of my t-shirt to some 3d template if so how to do that or I can only try the garments in MGN templates?

**Comment by chaitanya100100** [comment]
TailorNet t-shirt template can represent most t-shirts using style parameters. You can try finding style parameters which matches your particular example. Prediction from RGB image is out of the scope of TailorNet.
