### ISSUE TITLE
gammas

### ISSUE THREAD

**Issue by melih1996** [chaitanya100100/TailorNet#17]
What does gamma parm mean? For a garment, is there any way to modify gamma so that the created garment looks like the one we want to create?

**Comment by chaitanya100100** [comment]
Gamma parameters handle garment style (length, fit, sleeve length etc). You can try changing first 2 parameters from -2 to 2 and see its effect on garment. For example, first parameter of old-t-shirt will change its overall size and second will change sleeve length. Optimize these to get the desired garment.

**Comment by melih1996** [comment]
Thanks for your fast reply. Are some of the remaining parameters are responsible for the texture of the garment or all of them is about the geometric shape?

**Comment by chaitanya100100** [comment]
All of them deals with geometry of the garment. Texture is not part of the model.
But template garments are taken from MultiGarmentNetwork (https://github.com/bharat-b7/MultiGarmentNetwork) so all the textures from MGN wardrobe are applicable on TailorNet results.
