### ISSUE TITLE
multigarmentnetwork

### ISSUE THREAD

**Issue by melih1996** [chaitanya100100/TailorNet#19]
Hi, there are only 4 numbers to modify the garment. How to get a garment from multi garment network as said in oral presentation? I couldn't find any parameter other than gamma to modify the garment.

**Comment by chaitanya100100** [comment]
We have taken garment template _topology_ from MGN. If you have an MGN output garment and you want to get the gamma for that, then you can optimize gamma such that vertex to vertex distance is minimized.

**Comment by melih1996** [comment]
But I can only modify the color and sleeve lengths. In MGN, there are obj and pkl files. Which files do you mean?

**Comment by chaitanya100100** [comment]
I would really appreciate if you go through MGN and TailorNet properly to understand this better.
- As per [this](https://github.com/bharat-b7/MultiGarmentNetwork#dress-smpl-body-model-with-our-digital-wardrobe), MGN provides texture maps.
- Gamma parameters can change size and sleeve length both. 
- To apply texture map, you need to save obj or pkl file of the mesh with relevant texture information. Texture coordinates, texture maps, etc are provided by MGN. Vertex locations are predicted by TailorNet. You have all the components to create a textured output.

**Comment by melih1996** [comment]
Thanks for your reply again. Sorry, I am new for this topic and don't know the details. I looked at MGN and as you said there are obj files responsible for different types of garment. I couldn't get the part where Tailornet accepts an obj file. There are also pkl files and inside these files, there are beta,pose,gender parameters and also trans parameters which I don't know what it corresponds to. Is trans related to garment geometry or pkl files are only for the geometry of the smpl model who wears the corresponding garment. If you show where Tailornet accepts obj or pkl file I would really appreciate it. 
Thank you.

**Comment by melih1996** [comment]
Hi, is there any way to do texture mapping by using the templates in multi garment network without any manual stuff like a direct way using python API?

**Comment by ranorzh** [comment]
> 嗨，有没有什么方法可以通过使用多服装网络中的模板来进行纹理映射，而无需任何手动操作，例如使用 python API 的直接方式？
Have you fixed this problem?
