### ISSUE TITLE
pose doesn't exist

### ISSUE THREAD

**Issue by lixincheng4026** [chaitanya100100/TailorNet#2]
Thanks for your excellent work.
I download the dataset as you suggested. When I trained the base_trainer, it tells me that some data of t-shirt_male doesn't exist.

../TailorNet_dataset-master/data/t-shirt_male/pose/006_023/unposed_002.npy doesn't exist.
../TailorNet_dataset-master/data/t-shirt_male/pose/006_016/unposed_009.npy doesn't exist.
../TailorNet_dataset-master/data/t-shirt_male/pose/006_016/unposed_013.npy doesn't exist.
../TailorNet_dataset-master/data/t-shirt_male/pose/006_006/unposed_009.npy doesn't exist.
../TailorNet_dataset-master/data/t-shirt_male/pose/006_006/unposed_013.npy doesn't exist.

Well, it finished training anyway. But when I trained the lf_trainer, the same issue came up.  And then it just finished without training the lf_trainer. I have no idea of what happened, could you kindly look through my problem. Thanks in advance.

../TailorNet_dataset-master/data/t-shirt_male/pose/006_023/unposed_002.npy doesn't exist.
../TailorNet_dataset-master/data/t-shirt_male/pose/006_016/unposed_009.npy doesn't exist.
../TailorNet_dataset-master/data/t-shirt_male/pose/006_016/unposed_013.npy doesn't exist.
../TailorNet_dataset-master/data/t-shirt_male/pose/006_006/unposed_009.npy doesn't exist.
../TailorNet_dataset-master/data/t-shirt_male/pose/006_006/unposed_013.npy doesn't exist.
Using Smoothing in the dataset
../TailorNet_dataset-master/data/t-shirt_male/pose/006_023/unposed_002.npy doesn't exist.
../TailorNet_dataset-master/data/t-shirt_male/pose/006_016/unposed_009.npy doesn't exist.
../TailorNet_dataset-master/data/t-shirt_male/pose/006_016/unposed_013.npy doesn't exist.
../TailorNet_dataset-master/data/t-shirt_male/pose/006_006/unposed_009.npy doesn't exist.
../TailorNet_dataset-master/data/t-shirt_male/pose/006_006/unposed_013.npy doesn't exist.
../TailorNet_dataset-master/data/t-shirt_male/pose/007_011/smooth_unposed_000.npy doesn't exist.

**Comment by zycliao** [comment]
Hi. Some unposed_*.npy don't exist because their simulation went wrong and they're not included in the dataset. The data loader will simply ignore them. Since only few sequences don't exist, it won't affect the training.
As for 'smooth_unposed_*.npy doesn't exist', we apologize for missing these files. They're now included and you can download the dataset again. If it is hard for you to download the whole dataset again, let me know and I'll pack and send you those missed files.

**Comment by lixincheng4026** [comment]
Thanks. I have re-downloaded the dataset, it works fine.  Thanks for your brilliant work again. I will closed it.
