### ISSUE TITLE
Real time Rendering using WebGL. Or any other way to visualize the data? Like in a Game Engine? (Unity or any other?)

### ISSUE THREAD

**Issue by aapatre** [chaitanya100100/TailorNet#20]
Is it possible to directly render the result in web based graphic libraries in real time, instead of using Blender?

**Comment by chaitanya100100** [comment]
Yes, it is possible to run TailorNet real-time and stream its results using any renderer. It might require significant engineering effort to put the pieces together.
Do note that we provide TailorNet code and data for research purposes only so it is out of the scope of this repository.

**Comment by aapatre** [comment]
Thank you!
