### ISSUE TITLE
How is the data (character model, cloth animation, pose/character animation, etc.) passed to Blender? And how is the character draped?

### ISSUE THREAD

**Issue by aapatre** [chaitanya100100/TailorNet#23]

**Comment by chaitanya100100** [comment]
Go through this function which calls for visualization: https://github.com/chaitanya100100/TailorNet/blob/ff23afefd70aee394ac107a153989db714efb082/visualization/blender_renderer.py#L126

Main blender render function is here: https://github.com/chaitanya100100/TailorNet/blob/ff23afefd70aee394ac107a153989db714efb082/visualization/blender_renderer.py#L8
We have .blend file with camera and material already set up.

Go through tutorials and documentation of Blender Python API to know how python works in blender.

To answer your specific questions,
- Character model and cloth model (which is output of TailorNet) is saved as obj file to a temporary location which is then read by blender.
- We don't need to pass pose.
- We don't pass animation. Rather we merge per frame renderings to make a video.
- Output of TailorNet is naturally draped cloth on given body. So we need to just load them in blender and render it.


~ Chaitanya

**Comment by aapatre** [comment]
Thanks a lot, I will check these out!
Also, amazing work with your research! : ) @chaitanya100100
