### ISSUE TITLE
process gets killed while loading weights after running 'python run_tailornet.py'

### ISSUE THREAD

**Issue by NirajWan** [chaitanya100100/TailorNet#24]
![Screenshot from 2021-02-19 14-32-33](https://user-images.githubusercontent.com/69183705/108483080-4d3c0b00-72c0-11eb-92aa-048552e5abe3.png)

Process gets killed while loading weights, after running `python run_tailornet.py`

Gender: male
Cloth style: short-pant

Apparently it gets killed while loading 'tn_orig_ss2g'

The exact same happens in case of t-shirt female.

And it seems like an Out of Memory Error.

Any idea how to fix this?

![Screenshot from 2021-02-19 17-15-54](https://user-images.githubusercontent.com/69183705/108500702-33a5be00-72d6-11eb-9817-a4593e49c592.png)

**Comment by NirajWan** [comment]
The same happens for t-shirt female weights:

![Screenshot from 2021-02-19 16-30-56](https://user-images.githubusercontent.com/69183705/108496378-f4746e80-72cf-11eb-88ea-9b7bbec57404.png)

**Comment by chaitanya100100** [comment]
It means that you might not have sufficient GPU memory (or RAM if you are working without GPU) for the model to load. Can you list the specs of your machine - specifically RAM and GPU memory?

**Comment by NirajWan** [comment]
Thanks, just fixed the issue by terminating few processes. It execution was successful but got another issue while rendering:

![Screenshot from 2021-02-19 17-49-02](https://user-images.githubusercontent.com/69183705/108503687-cfd1c400-72da-11eb-9ec5-652864438717.png)

**Comment by chaitanya100100** [comment]
A simple, very simple google search will give you solutions like below telling that it is the problem of scipy version.

https://github.com/benjiebob/SMALify/issues/22

https://stackoverflow.com/questions/65628149/ratcave-scipy-spatial-transform-rotation-rotation-object-has-no-attribute-a

**Comment by NirajWan** [comment]
Thanks @chaitanya100100 :raised_hands:
