### ISSUE TITLE
garment to body

### ISSUE THREAD

**Issue by melih1996** [chaitanya100100/TailorNet#25]
Hi, did you train any model to match garment and body vertices which is the "I" parameter in this equation 3.3  below?
TG(β, θ, D) = I T(β, θ) + D

**Comment by chaitanya100100** [comment]
We take a submesh of SMPL template (a cutout from body template) as our garment template.
"The indicator matrix I ∈ Z ^{m×n} evaluates to I[i,j] = 1 if garment vertex i ∈ {1 . . . m} is associated with body shape vertex j ∈ {1 . . . n}." That is, if vertex j of the body is same as vertex i of the garment then I[i,j] = 1.

**Comment by melih1996** [comment]
Thanks for your reply, it seems you have applied a different strategy for skirts. Did you calculate skinning weights for the skirt with data from PBS based method then train a model?
