### ISSUE TITLE
tailornet dataset

### ISSUE THREAD

**Issue by mfikryrizal** [chaitanya100100/TailorNet#28]
Why do we need to download the large datasets? The model weights are already provided in this repo's readme.

**Comment by chaitanya100100** [comment]
Hello @mfikryrizal .

TailorNet model requires betas (body shape parameters) and gammas (garment style parameters) from the dataset. That is why dataset download is required.

In our dataset organization, we haven't yet separated those parameters from the 3D garment groundtruth(which is responsible for most of storage space) i.e. everything is provided together. I have transferred your query to @zycliao who handles dataset repository. Till then, dataset download will be required for running inference.

Thanks.

**Comment by mfikryrizal** [comment]
Thank you for the response @chaitanya100100 . I had another look at the code (going through run_tailornet.py) and I noticed that `pose` dataset files -the largest files- are not used in instantiating any model. So is it safe to say that I can just remove them if I use my own SMPL parameters, while `shape` and `style_shape` must be retained?

**Comment by zycliao** [comment]
> Thank you for the response @chaitanya100100 . I had another look at the code (going through run_tailornet.py) and I noticed that `pose` dataset files -the largest files- are not used in instantiating any model. So is it safe to say that I can just remove them if I use my own SMPL parameters, while `shape` and `style_shape` must be retained?

Yes. `pose` is only for training, so you can remove them for just inference. I will pack files that are used for inference later.

**Comment by mfikryrizal** [comment]
@zycliao That's great! Thank you for the response. I'm done with the questions
