### ISSUE TITLE
Multi Mesh registration.

### ISSUE THREAD

**Issue by Vikas-Sony** [chaitanya100100/TailorNet#29]
Hi,

Can i get a sample code for doing multi mesh registration as i am having a hard time figuring how to do that? I am trying to use my 3D scans and hoping to register those to tailornet data.

Thanks for the great work tho.

**Comment by chaitanya100100** [comment]
Hi @Vikas-Sony ,
We take our template from [MGN](https://github.com/bharat-b7/MultiGarmentNetwork) which uses multi-mesh registration to generate data. So multi-mesh registration is out of the scope of this repository and TailorNet method.
Thanks.
