### ISSUE TITLE
how to combine up cloth and pants

### ISSUE THREAD

**Issue by xiaofanglegoc** [chaitanya100100/TailorNet#3]
Hi @chaitanya100100,
   Thanks a lot for sharing the code and it makes very interesting step in the subject of dressing up SMPL model. In your codes, we can only render up cloth, do you  mind to shed more codes on how to dress the SMPL model completely?

**Comment by chaitanya100100** [comment]
Hi @xiaofanglegoc ,

Thanks for your interest in our work. This repository is for TailorNet training code. We provide some code for some quick visualization only.

Given that, it's not hard to dress both upper and lower cloth on SMPL. You can supply body, predicted upper cloth and lower cloth to [this](https://github.com/chaitanya100100/TailorNet/blob/e44673a3e373411a876beb4acdc814057dcf5463/visualization/blender_renderer.py#L126) function. To solve interpenetration, you can solve interpenetration for lower garment and body. And then combine both to solve their interpenetration with upper garment.

**Comment by melih1996** [comment]
Hi @chaitanya100100  What are lower_gc and upper_gc in this function?
