### ISSUE TITLE
Missing SMPL Models

### ISSUE THREAD

**Issue by juch001** [chaitanya100100/TailorNet#32]
Hi, from the code, it requires the following SMPL models. 
SMPL_PATH_NEUTRAL = '/BS/RVH/work/data/smpl_models/neutral/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl'
SMPL_PATH_MALE = '/BS/RVH/work/data/smpl_models/lrotmin/lbs_tj10smooth6_0fixed_normalized/male/model.pkl'
SMPL_PATH_FEMALE = '/BS/RVH/work/data/smpl_models/lrotmin/lbs_tj10smooth6_0fixed_normalized/female/model.pkl'

I download the SMPL_python_v.1.0.0.zip, but inside the folder, only has the male and female models. No neutral model. could you please suggest where  to get the neutral one? And from the names above, seems the SMPL Models of male and female have been normalized. Do I understand right, or the models are same as the downloaded ones? thanks.

**Comment by chaitanya100100** [comment]
TailorNet is only available for male and female model. You can remove SMPL_PATH_NEUTRAL variable.

SMPL models are the same as the ones you downloaded.
