### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by zahrahosseini99** [chaitanya100100/TailorNet#33]
Hi, I want to try TailorNet on my data.
What is the input format? A 3D obj or a 2D image?
If it is 3D, should I first use something like [MGN ](https://virtualhumans.mpi-inf.mpg.de/mgn/) to produce a 3D obj of my 2D input?
for example, if I want to use the below woman as a body shape input and the coat image as a garment and as a result see the coat on the woman.
![8790E227-2883-48DB-B694-76074FD31B71](https://user-images.githubusercontent.com/48201383/115935549-a97dff80-a4a8-11eb-968d-69683e2aacd1.jpg)
![main-qimg-3d4ae1dcd8616ebe58bd77a88c172ad1](https://user-images.githubusercontent.com/48201383/115935595-c9152800-a4a8-11eb-928f-6495cf809658.png)

 
@chaitanya100100

**Comment by chaitanya100100** [comment]
Input to TailorNet is SMPL body pose parameters, SMPL body shape parameters and garment style parameters. Read the paper for details.
We don't provide coat garment - TailorNet is available for shirt, t-shirt, pants, skirt, short-pants.
MGN can output 3D garment (predicting body pose and shape as an intermediate step) from few input rgb images. TailorNet can take that pose and shape as input. You can use any reasonable garment style parameters or do a simple optimization to get garment style parameters corresponding to 3D garment output of MGN.
