### ISSUE TITLE
can't run run_tailornet.py

### ISSUE THREAD

**Issue by hbwanghang** [chaitanya100100/TailorNet#34]
Hi,I reproduced your code according to your idea, and the result appeared such an error. What should I do?
![image](https://user-images.githubusercontent.com/20834302/116019377-a59fd800-a676-11eb-967f-4c851f7644e0.png)
And when I follow the steps to train the model, this error will be reported. What should I do?
![image](https://user-images.githubusercontent.com/20834302/116019387-adf81300-a676-11eb-8902-5c15f0a2a5b8.png)

**Comment by chaitanya100100** [comment]
For the first error, it is clear from the error that you need to set path properly. Do you have `.../zc/data/old-t-shirt_female_weights/skirt_female_weights/tn_orig_hf/skirt_female/005_020/params.json` available? Make sure that you set proper paths in global_var.py

**Comment by chaitanya100100** [comment]
For the training error, you need to provide some more information for me in order to solve your error.
I see that you are running hf_trainer for tshirt male. Can you tell me for which style shape you are getting this error?

**Comment by hbwanghang** [comment]
> For the first error, it is clear from the error that you need to set path properly. Do you have `.../zc/data/old-t-shirt_female_weights/skirt_female_weights/tn_orig_hf/skirt_female/005_020/params.json` available? Make sure that you set proper paths in global_var.py

My path setting and data set download are performed according to the prompts in your readme. But there is no such folder as 005_020 .The first picture is missing the picture of the folder of 005_020, and the second picture is the picture of my path setting, please tell me how to modify it, thank you 
![image](https://user-images.githubusercontent.com/20834302/116063978-27fcbc00-a6b8-11eb-8c2e-4f6d7ae8bb76.png)
![image](https://user-images.githubusercontent.com/20834302/116064106-4793e480-a6b8-11eb-89ef-fcde25eae5da.png)

**Comment by chaitanya100100** [comment]
There seems to be an issue with the way you have set up model weights. In your path, you have mixed tshirt and skirt. Check [this](https://github.com/chaitanya100100/TailorNet/blob/0adae42b0b28b5bfacd9951ac542281fad96b110/models/tailornet_model.py#L93) to see how model weights are picked up according to garment class and gender. You should set up downloaded weights like this:
```
--MODEL_WEIGHTS_PATH
------old-t-shirt_female_weights
----------tn_orig_lf
----------tn_orig_hf
----------tn_orig_ss2g
------skirt_female_weights
----------tn_orig_lf
----------tn_orig_hf
----------tn_orig_ss2g
```

**Comment by hbwanghang** [comment]
> There seems to be an issue with the way you have set up model weights. In your path, you have mixed tshirt and skirt. Check [this](https://github.com/chaitanya100100/TailorNet/blob/0adae42b0b28b5bfacd9951ac542281fad96b110/models/tailornet_model.py#L93) to see how model weights are picked up according to garment class and gender. You should set up downloaded weights like this:
> 
> ```
> --MODEL_WEIGHTS_PATH
> ------old-t-shirt_female_weights
> ----------tn_orig_lf
> ----------tn_orig_hf
> ----------tn_orig_ss2g
> ------skirt_female_weights
> ----------tn_orig_lf
> ----------tn_orig_hf
> ----------tn_orig_ss2g
> ```
I downloaded the skirt data set and solved the previous bug, but a new bug occurred. Is this because I didn’t run hf_trainer for tshirt male to complete it? 
![image](https://user-images.githubusercontent.com/20834302/116170003-810c3480-a738-11eb-9b7b-66b92b09da47.png)
![image](https://user-images.githubusercontent.com/20834302/116170015-86697f00-a738-11eb-97f5-2f5f96faaa24.png)

**Comment by hbwanghang** [comment]
> For the training error, you need to provide some more information for me in order to solve your error.
> I see that you are running hf_trainer for tshirt male. Can you tell me for which style shape you are getting this error?

000_001or000_000
