### ISSUE TITLE
Minimizing model sizes

### ISSUE THREAD

**Issue by mfikryrizal** [chaitanya100100/TailorNet#35]
![Screenshot from 2021-05-05 18-43-10](https://user-images.githubusercontent.com/58203706/117130123-30e54000-add2-11eb-9953-3016c41111db.png)
DISCLAIMER: I am deploying Tailornet for academic dissertation

1) I have applied a simple dynamic quantization which reduced the model sizes to 1/4. How do I evaluate the accuracy vs original model weights?

2) Applying any sort of PyTorch pruning even with very very small amount results in all weights to be removed. Any idea why this happens?

**Comment by chaitanya100100** [comment]
1. Use the evaluate function (link given below). It's fairly easy to understand and modify. You will need to set garment class, gender and your model as runner. It will evaluate on the test set of the data.
https://github.com/chaitanya100100/TailorNet/blob/0adae42b0b28b5bfacd9951ac542281fad96b110/utils/eval.py#L21
2. You need to provide some more details in order for us to comment anything. Which model are you talking about - lf, hf, ss2d? Which garment? Which gender? What procedure did you use to prune? How much pruning happened?

**Comment by chaitanya100100** [comment]
... and what were the evaluation results after pruning (if results drop drastically with little pruning, then all weights are important. Else the learned weights are sparse)?

**Comment by chaitanya100100** [comment]
How can loading time goes up when the model is smaller now?
And did you try with stronger quantization?

**Comment by mfikryrizal** [comment]
> How can loading time goes up when the model is smaller now?
This baffled me as well. Some on PyTorch forum has also observed this behavior. For reference I am running PyTorch on CPU on a 6 core EPYC 7542 VPS.

> And did you try with stronger quantization?
I was looking for simple ways to increase performance following the scope of my project - I am simply not interested in retraining/calibrating the model. Nevertheless I would look into it if all else fails.
