### ISSUE TITLE
vt and face information of the prediction result

### ISSUE THREAD

**Issue by juch001** [chaitanya100100/TailorNet#36]
Hi,

If change the prediction output as .obj files, how would I create the vt and f information inside the .obj file? Please kindly send me examples/templates of each garment if you have them. 

Besides, is there a way to change the number of the vertices and faces for prediction output. Thank you so much.

Best Regards,
JC

**Comment by chaitanya100100** [comment]
Neural network works on a fixed output dimension. So there is no way to change the number of vertices and faces in the output.
We take our template from MGN(https://github.com/bharat-b7/MultiGarmentNetwork) which comes with those texture coordinates. So you should look into that. You can export obj with textures like this:

v = <Nx3 output vertices>
f = <Fx3 fixed faces from template>
ft = <texture coordinates from template>
vt = <texture coordinates from template>

ms = Mesh(v=v, f=f, vt=vt, ft=ft)
ms.save_obj("result.obj")

**Comment by juch001** [comment]
thank you.

**Comment by juch001** [comment]
Hi,

Could you please advise what the 'ft' is? I went through the documents
inside the link and only found vt and f but not ft. Thanks.

Best Regards,
JC

**Comment by chaitanya100100** [comment]
Answered here: https://github.com/chaitanya100100/TailorNet/issues/37
