### ISSUE TITLE
Old-t-shirt for male dataset

### ISSUE THREAD

**Issue by juch001** [chaitanya100100/TailorNet#38]
Hi,

Do you have the dataset for old-t-shirt for male? If have, could you please kindly upload it? Thanks so much.

**Comment by chaitanya100100** [comment]
Hello, 
There is no old-t-shirt for male. You can use t-shirt for male. 
Old-t-shirt for female is provided if someone wants to reproduce results from the paper exactly. See this : https://github.com/zycliao/TailorNet_dataset#dataset-description
