### ISSUE TITLE
time to load the dataset is too long when training

### ISSUE THREAD

**Issue by NguyenTriTrinh** [chaitanya100100/TailorNet#40]
I follow the default setting to train the model, and I found it took long time to load the dataset during training, almost more than five minutes.  Is there something wrong?

**Comment by chaitanya100100** [comment]
It depends. To load the entire dataset of all style shapes and all poses, it might take around a minute depending upon the resources. But for loading data for one style shape, it should be quicker than that. You need to give more information.
- Which model were you trying to train? Baseline, Low frequency model or one of the high frequency models?
- Does the training machine have direct access to the dataset or is it transferring from network?
- Is 5 minutes just for loading the data or does it also include loading model into GPU?

~ Chaitanya

**Comment by NguyenTriTrinh** [comment]
Hi, Chaitanya
Thanks for you detailed quick reply. Today I tried to train the model again and the time to load the entire dataset is normal now, I think It's the reason of my machine. Now I will close the issue.
