### ISSUE TITLE
How to use a single picture as input

### ISSUE THREAD

**Issue by hbwanghang** [chaitanya100100/TailorNet#41]
hi，is it allowed to use a single picture as input?If so, how can I do it?

**Comment by chaitanya100100** [comment]
TailorNet is an animatable garment model controlled by body pose, shape and garment style parameters. It doesn't operate on image input so your use case is out of the scope of TailorNet.

**Comment by hbwanghang** [comment]
> TailorNet is an animatable garment model controlled by body pose, shape and garment style parameters. It doesn't operate on image input so your use case is out of the scope of TailorNet.

thank you very much.
