### ISSUE TITLE
model for garment generation based on style-shape

### ISSUE THREAD

**Issue by juch001** [chaitanya100100/TailorNet#42]
Hi Author,

Based on the information in the paper, seems there is a model which can be used for generating different style garment mesh based on style-shape. Could you please share this model to us? thanks.

**Comment by chaitanya100100** [comment]
Hello,

There is no model to generate style garment from input style-shape. I am not sure what you mean. Can you elaborate more or point to the section in the paper?

You may also want to check this section of dataset directory: https://github.com/zycliao/TailorNet_dataset#dataset-description
