### ISSUE TITLE
run_tailornet.py render fails

### ISSUE THREAD

**Issue by AlyanQ** [chaitanya100100/TailorNet#45]
```
Read blend: /home/arash/Desktop/TailorNet/./visualization/scene.blend
['/usr/lib/blender/blender', '/home/arash/Desktop/TailorNet/visualization/blender_renderer.py', '--', '--body', '/tmp/body.obj', '--gar', '/tmp/gar.obj', '--outpath', '/home/arash/Desktop/TailorNet/outputs/img_0002.png', '--gar_classes', 'pant']
usage: blender [-h] [--outpath OUTPATH] [--body BODY [BODY ...]]
               [--gar GAR [GAR ...]]
               [--gar_classes GAR_CLASSES [GAR_CLASSES ...]]
blender: error: unrecognized arguments: /home/arash/Desktop/TailorNet/visualization/blender_renderer.py -- --body /tmp/body.obj --gar /tmp/gar.obj --outpath /home/arash/Desktop/TailorNet/outputs/img_0002.png --gar_classes pant
```

Trying to run the render on the predicted garments gives the above error. It seems to throw an error about unrecognised arguments but I'm not sure what exactly it's complaining about. Any help would be appreciated, since this is the final step remaining to achieve inference. Thanks

**Comment by AlyanQ** [comment]
The issue was my blender version was too high (2.91). Downgrading Blender back to 2.79 fixed the issue. Although now, trying to render frames with any other garment type other than T-Shirt throws errors.

**Comment by chaitanya100100** [comment]
Yes. Blender version needs to be 2.79 .
I can't help you if I don't know what the error is. Can you describe your error?

**Comment by AlyanQ** [comment]
```
found bundled python: /snap/blender/20/2.79/python
Read blend: /home/arash/Desktop/TailorNet/./visualization/scene.blend
['/snap/blender/20/./blender', '--body', '/tmp/body.obj', '--gar', '/tmp/gar.obj', '--outpath', '/home/arash/Desktop/TailorNet/outputs/img_0022.png', '--gar_classes', 'pant']
Namespace(body=['/tmp/body.obj'], gar=['/tmp/gar.obj'], gar_classes=['pant'], outpath='/home/arash/Desktop/TailorNet/outputs/img_0022.png')
Traceback (most recent call last):
  File "/home/arash/Desktop/TailorNet/visualization/blender_renderer.py", line 255, in <module>
    tex_num += [dd[gc] for gc in args.gar_classes]
  File "/home/arash/Desktop/TailorNet/visualization/blender_renderer.py", line 255, in <listcomp>
    tex_num += [dd[gc] for gc in args.gar_classes]
KeyError: 'pant
```

Running `run_tailornet.py` works fine with all garment classes but running `run_tailornet.py render` fails with the above error with any garment class other than T-Shirt. My blender version is 2.79 as well.

**Comment by chaitanya100100** [comment]
It's 'pants', not 'pant'.
https://github.com/chaitanya100100/TailorNet/blob/0adae42b0b28b5bfacd9951ac542281fad96b110/visualization/blender_renderer.py#L243

**Comment by AlyanQ** [comment]
> 

Thanks, I found the problem. In TailorNetDataset and `run_tailornet()`, it uses the tag 'pant' whereas in `render()` it uses 'pants'.

**Comment by chaitanya100100** [comment]
Oh right! That's indeed a silly and easy-to-fix bug. Thanks for the heads up. Corrected now.
