### ISSUE TITLE
How can we use our own meshes to apply garment meshes on top?

### ISSUE THREAD

**Issue by AlyanQ** [chaitanya100100/TailorNet#46]
According your your readme, you have mentioned that the program is using random inputs and that we can play with different inputs. But you have not explicitly mentioned what the exact inputs that the TailorNet network takes to make a prediction. For example, can we only use SMPL model to apply garment meshes on the model? Is there a method to use my own model that I created using SMPL model and apply the garment meshes on top of that? Please guide, thanks.

**Comment by chaitanya100100** [comment]
Input to tailornet is pose, shape and garment style parameters (thetas, betas and gammas respectively). If you want to know more about what these parameters mean, you should check out the paper.
You can specify the parameters of your own liking here (along with gender and garment type): https://github.com/chaitanya100100/TailorNet/blob/master/run_tailornet.py#L75-L77

What do you mean by 'my own model that I created using SMPL model' ? If you meant the pose and shape, then you can directly use that as input to tailornet.
