### ISSUE TITLE
Need guidance

### ISSUE THREAD

**Issue by omarmohamed101** [chaitanya100100/TailorNet#48]
I ran the code successfully and thanks for the amazing work.
i have 2 questions
section 6.3 in the paper says that **we can also transfer the textures from real scan on our predictions.** can you suggest a method of doing that?

Also how can i control the garment size? i couldn't figure out how from the paper.

Excuse me if the questions seem naive as i don't have much experience in the field. Thanks in advance

**Comment by chaitanya100100** [comment]
Thank you for your interest in TailorNet.

1. Garment templates are taken from MGN (https://github.com/bharat-b7/MultiGarmentNetwork). MGN provides textures in its dataset. So you can take vertices predicted by TailorNet, texture coordinates from MGN dataset and texture image from MGN dataset to create a textured 3D model (which you can save in obj or ply format).

2. Garment styles can control garment size. For each garment, try changing first or second garment style parameter and see its effect on generated garment. For most garment, it should allow you to change size.

I would recommend reading the paper and playing with run_tailornet.py script (using different values of pose, shape and style parameters) to see what TailorNet can and can't do.
