### ISSUE TITLE
what is the different between the old t-shirt and t-shirt?

### ISSUE THREAD

**Issue by wells-wei-wei** [chaitanya100100/TailorNet#5]

**Comment by chaitanya100100** [comment]
This is already explained [here](https://github.com/zycliao/TailorNet_dataset#dataset-description), but I will repeat anyway.

[MGN](https://github.com/bharat-b7/MultiGarmentNetwork) released new garment templates which are better than previous versions (we use MGN garment templates as mentioned in the paper). So we use these new templates for all TailorNet garments (t-shirt, pants, shirt).

However, old-t-shirt was used for generating results (qualitative and quantitative) mentioned in the paper. So we provide old-t-shirt if someone wants to compare with TailorNet directly.
