### ISSUE TITLE
Regarding psbody-mesh installation

### ISSUE THREAD

**Issue by abhinav-1707** [chaitanya100100/TailorNet#53]
Respected sir,
Our group is trying to use your model Tailornet in our R and D project on AR based 3D try-on. But while running in windows it is getting tons of error. If you are available and could help is that will be very helpful. Also do pybody-mesh works only on linux and mac os because I am getting errors every time I am trying to install it in VS code?

**Comment by chaitanya100100** [comment]
Thanks for your interest in TailorNet. Do take care of the license before you use model or dataset.
I haven't tried it on windows but I don't see any reason why it shouldn't work. You should try asking for help on psbody-mesh repository. And don't forget to include your error message -- noone can help you if they don't know what error you are getting.
Thanks.
