### ISSUE TITLE
Control size of garments 

### ISSUE THREAD

**Issue by shahendahamdy** [chaitanya100100/TailorNet#54]
I want to know how to control the size of garments 
for example, I want to get sizes like small, medium, large, etc...
I understand that the garment creation depends on both beta and gamma parameters, what is the relation between them?

(I want to get a 3d body with a specific shape wearing multiple sizes of t-shirts to see how these sizes look)

**Comment by chaitanya100100** [comment]
You can change gamma parameters to change style. Usually first gamma parameter controls the size of garment. To visualize, you can pass zero shape and A-pose.
