### ISSUE TITLE
intersecting multiple garments

### ISSUE THREAD

**Issue by Mohamed-Fathy-Salah** [chaitanya100100/TailorNet#55]
when i try to combine 2 garments (top, bottom) the garments intersect.

i tried solving it by concatenation of the body and the bottom garment.
`body_bottom_garment = body.concatenate_mesh(bottom_garment)` 

then remove the interpenetration between the combined mesh with the top garment.
`top_garment = remove_interpenetration_fast(top_garment, body_bottom_garment)`

however it didn't solve the problem.

here is an example on t-shirt_female with short-pant_female
![image](https://user-images.githubusercontent.com/60598620/173362920-ff8a6329-edc9-43fa-8f27-3ded529b7ebc.png)

any idea how to fix this problem?
thanks.

**Comment by chaitanya100100** [comment]
The way interpenetration removal works is as follows: for each garment vertex, we find the nearest body surface point and normal of that body surface point. Then using some simple vector math, we can decide whether that garment vertex is inside or outside. For all inside garment vertices, we try to pull them out while ensuring that the garment laplacian is maintained. You can see the code here:

https://github.com/chaitanya100100/TailorNet/blob/09e2830d3f609c4056bc602cb7f87d820282f95e/utils/interpenetration.py#L53

Now coming to your issue, there are many potential problems you should look into. One problem can be that the combined pant-body mesh doesn't have 'good' normals.

Another problem can be this: When we merge body and pant, we create a mesh with some non-trivial geometry around waist. There are two surfaces (body and pant) around waist. So when you call interpenetration removal between shirt and bodypant, some shirt vertices are matched with body surface (which is inside the pant surface). And hence the penetration is not removed. You can process bodypant mesh such that this doesn't happen (like removing body vertices which are inside shirt).

You can also try multiple interpenetration solver in succession: like pant-body, shirt-body and then shirt-pantbody.
