### ISSUE TITLE
Predicted Displacements

### ISSUE THREAD

**Issue by theAdityaRamesh** [chaitanya100100/TailorNet#59]
@chaitanya100100 @zycliao could you please tell me 

1. Does the displacements in the variable `pred_verts_d` over here correspond to the displacements to the SMPL vertices displacements in the canonical pose as illustrated in figure2 of the paper or are they the displacements in the posed space after applying skinning ?

```
    pred_verts_d = tn_runner.forward(
                thetas=torch.from_numpy(theta_normalized[None, :].astype(np.float32)).cuda(),
                betas=torch.from_numpy(beta[None, :].astype(np.float32)).cuda(),
                gammas=torch.from_numpy(gamma[None, :].astype(np.float32)).cuda(),
            )[0].cpu().numpy()
```

If it is the displacements in the posed space can you please tell me how to get displacements in the canonical space prior to applying skinning ?

![image](https://github.com/chaitanya100100/TailorNet/assets/35490721/931970e3-4366-4422-8392-a4ce4a0fdd78)

**Comment by chaitanya100100** [comment]
Those displacements are in unposed space.

**Comment by theAdityaRamesh** [comment]
@chaitanya100100 @zycliao  Thanks, for your quick reply. Can you tell me where in the smpl.run() function is the skinning happening ? Also is the unposed pose an A pose or T pose ?.

**Comment by chaitanya100100** [comment]
See models/smpl4garment.py .
In short, each time we change base template vertices by adding the displacements and then use standard SMPL skinning. Unposed pose is T-pose. A pose is used as the rest pose for data simulation.
