### ISSUE TITLE
use smplx model problem

### ISSUE THREAD

**Issue by tomyjack** [chaitanya100100/TailorNet#6]
thanks for your code, greate work!!
i use expose model params to test this code,
when i use the betas, is not right, looks like the shape is different from smplx
the body_pose i change to check the pose is ok
please help

**Comment by chaitanya100100** [comment]
In SMPL, the meaning of each beta parameter is different for male, female and neutral model. So I suspect that with SMPLX will also have different betas. (Betas are just PCA parameters.)

You can do a simple manual check by comparing the output of SMPL and SMPLX models with the same beta parameters. If both are indeed different, you might need to come up with a transformation to convert SMPLX betas to SMPL betas.

**Comment by tomyjack** [comment]
@chaitanya100100 thanks for your advise.
i test the param for smpl and smplx,find neutral model is different by some betas, but the male and female is almost the same, so i check gender before doing this process. finally finish my work.
thanks!

**Comment by chaitanya100100** [comment]
Cool. Glad that it finally worked.

**Comment by tomyjack** [comment]
@chaitanya100100 new questions:the trans in smpl is 3 floats, the smplx has not that var,
This is what I found out when I was doing different action tests

**Comment by chaitanya100100** [comment]
trans is translation. It is not required for TailorNet. We assume it to be 0.

**Comment by tomyjack** [comment]
ok, i see
i use the global_orient and body_pose to slove the problem.
thanks for your advise

**Comment by BukuBukuChagma** [comment]
> ok, i see i use the global_orient and body_pose to slove the problem. thanks for your advise

Hi, smpl and smplx have different thetas length, smpl(72) while smplx (3 orient, 63 pose = 66). How did u use smplx thetas in this tailornet?

**Comment by chaitanya100100** [comment]
There are several types of smpl models: smpl, smpl+h, smplx. The library smplx provides a way to access all those smpl models by providing appropriate smpl model file. We use basic smpl which has 24 joints (one global rotation at root and 23 others). See this (https://github.com/chongyi-zheng/SMPLpp/blob/master/docs/media/kinematic_tree.png) for reference.

The one you are refering to is most likely smpl+h where it has expressive hands. It removes joint number 22 and 23 from smpl (see the image linked above) and puts many hand joints to make hands animatable.
