### ISSUE TITLE
Please update the "short-pant" type in the "garment_class_info.pkl" file.

### ISSUE THREAD

**Issue by LiuXinqi12** [chaitanya100100/TailorNet#8]
Hello, thank you for your excellent work. I want to use the "short-pant" clothing model, but found that it is not in the "garment_class_info.pkl" file. Would you mind updating it?  Thank you very much!

**Comment by lokender** [comment]
Hi Chaitanya,

I was looking at blender_renderer.py. Can you please add default arguments ?. e.g what should be the input to the following arguments. --body, --gar, --garment_class 

Thank you for this wonderful work.

**Comment by zycliao** [comment]
Hi, the updated one is in ```dataset_meta.zip``` here https://nextcloud.mpi-klsb.mpg.de/index.php/apps/files?dir=/TailorNet&fileid=5058113

**Comment by LiuXinqi12** [comment]
OK, thank you very much!
