### ISSUE TITLE
visualization/blender_renderer.py default arguments

### ISSUE THREAD

**Issue by lokender** [chaitanya100100/TailorNet#9]
Hi Chaitanya,

I was looking at blender_renderer.py. Can you please add default arguments ?. e.g what should be the input to the following arguments. --body, --gar, --garment_class 

Thank you for this wonderful work.

**Comment by chaitanya100100** [comment]
I am assuming that you have found the solution. You can look here for more info: https://github.com/chaitanya100100/TailorNet/blob/2209e95d6c66c7e2f9c2f8ef39fe1dbd67e46c7f/visualization/blender_renderer.py#L155

**Comment by lokender** [comment]
Thanks, Chaitanya
